USE [master]
GO

/****** Object:  Database [JobWorkManagement]    Script Date: 11-02-2020 03:13:23 PM ******/
CREATE DATABASE [JobWorkManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JobWorkManagement', FILENAME = N'F:\Technology\ASP.Net\Database\JobWorkManagement\JobWorkManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JobWorkManagement_log', FILENAME = N'F:\Technology\ASP.Net\Database\JobWorkManagement\JobWorkManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JobWorkManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JobWorkManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JobWorkManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JobWorkManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JobWorkManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JobWorkManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [JobWorkManagement] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [JobWorkManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JobWorkManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JobWorkManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JobWorkManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JobWorkManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JobWorkManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JobWorkManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JobWorkManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JobWorkManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [JobWorkManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JobWorkManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JobWorkManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JobWorkManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JobWorkManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JobWorkManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JobWorkManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JobWorkManagement] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [JobWorkManagement] SET  MULTI_USER 
GO

ALTER DATABASE [JobWorkManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JobWorkManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JobWorkManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JobWorkManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [JobWorkManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [JobWorkManagement] SET QUERY_STORE = OFF
GO

ALTER DATABASE [JobWorkManagement] SET  READ_WRITE 
GO

